spring:
  application:
    name: hello-spring-boot-admin
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/