spring:
  application:
    name: hello-spring-cloud-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 9411

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/