spring:
  application:
    name: hello-spring-cloud-config
  zipkin:
    base-url: http://localhost:9411
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/suchuner/spring-cloud-config.git
          search-paths: respo
          username: suchuner@163.com
          password: 9426498zy.
  boot:
    admin:
      client:
        url: http://localhost:8084

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/